/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.util.Random;

public class mainfile1 extends javax.swing.JFrame {
    
   


Timer time;
private static final int interval =1000;

private static int min =30;
private static int sec =0;
private int a;
private String[] quese=new String[11];
private String[] answere=new String[11];
private String[] quesm=new String[11];
private String[] answerm=new String[11];
private String[] quesh=new String[11];
private String[] answerh=new String[11];
private  int[] exc;
private  Random rand;
private final int max=10;
private final int minm=1;
private int num;
private boolean status=true;
private String level ="eazy";
private int count=0;
private String answer;
private int nextindex=1;
private int temp;
private String pass; 
private static  String Hex;

/**
     * Creates new form end
     */
    public mainfile1(String Hex) {
        this.Hex = Hex;
       
        queandans();
        
        initComponents();
        updatemydialog();
        
        jLabel2.setText(Hex);
        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        
        submit.setOpaque(false);
        submit.setContentAreaFilled(false);
        submit.setBorderPainted(false);
        
        jLabel5.setHighlighter(null);
      
        
        time = new Timer(interval,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                
            if (sec==0 ){
               sec=59;
                min--;
            }
           
            
            
                   if(min<10){
                     if(sec<10)
                    jLabel3.setText("0"+min+":0"+sec);
                      else
                         jLabel3.setText("0"+min+":"+sec); 
                   }
                   else
                    jLabel3.setText(min+":"+sec); 
                   
                    sec--;           
                        
               
            
            
            if(min==0 && sec==0)
            {   
                Toolkit.getDefaultToolkit().beep();
                time.stop();
                showMessage();
                
            }
            }
        });
        
                time.start();
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel5 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HAPPY HUNTING");
        setMaximumSize(new java.awt.Dimension(640, 500));
        setMinimumSize(new java.awt.Dimension(640, 500));
        setPreferredSize(new java.awt.Dimension(640, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/unlocek.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/locked.png"))); // NOI18N
        jButton2.setDoubleBuffered(true);
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 150, 60));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 140, 30));

        jLabel3.setFont(new java.awt.Font("Moon", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("00:00");
        jLabel3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, -1, -1, 40));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resume.png"))); // NOI18N
        submit.setAutoscrolls(true);
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submit.setFocusable(false);
        submit.setInheritsPopupMenu(true);
        submit.setMaximumSize(new java.awt.Dimension(25, 25));
        submit.setMinimumSize(new java.awt.Dimension(25, 25));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 30, 30));

        jLabel4.setFont(new java.awt.Font("Moon", 0, 24)); // NOI18N
        jLabel4.setText("Level :0000");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 60, 130, 30));

        jScrollPane1.setEnabled(false);

        jLabel5.setEditable(false);
        jLabel5.setColumns(20);
        jLabel5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel5.setRows(5);
        jLabel5.setBorder(null);
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(false);
        jScrollPane1.setViewportView(jLabel5);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 340, 220));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Moon", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Custom Size – 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        dojob();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        dojob();
    }//GEN-LAST:event_submitActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton2.setEnabled(false);
      updatemydialog();
       // new end().setVisible(true);
         //    this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public void updatemydialog(){
        jTextField1.setText("");
        count++;
        if(count==1){
            exc = new int[]{0,0,0,0,0,0,0,0};}
        if(count==7){
            nextindex=1;
            exc = new int[]{0,0,0,0,0,0,0,0};}
        if(count==13){
            nextindex=1;
            exc = new int[]{0,0,0,0,0,0,0,0};}
        if(count==19)
            showMessage2();
        temp=random(max, minm);
        while(temp==0){
           temp=random(max, minm); 
           if(exc[6]!=0){System.out.print(exc[6]);
               break;}
        }
        if(count<7){
        jLabel5.setText(quese[temp]);
         answer=answere[temp];
        jLabel4.setText("LEVEL : "+count);}
        else if (count>6 && count<13){
        jLabel5.setText(quesm[temp]);
         answer=answerm[temp];
        jLabel4.setText("LEVEL : "+count);}
        else if (count>12){
        jLabel5.setText(quesh[temp]);
         answer=answerh[temp];
        jLabel4.setText("LEVEL : "+count);}
    }
    
    public void showMessage(){
        JOptionPane.showMessageDialog(this,"Time is Over");
        pass=String.valueOf(count-1);
        new end(Hex+"Level "+pass).setVisible(true);
             this.setVisible(false);
    }
     public void showMessage2(){
        JOptionPane.showMessageDialog(this,"Congo! you complete all level");
        pass = jLabel3.getText();
        new end(Hex+pass).setVisible(true);
             this.setVisible(false);
    }
   public void dojob(){
     
            
        if(answer.equals(jTextField1.getText())){
          
            jButton2.setEnabled(true);
        }
        else{
           //jButton2.setIcon(imageLock);
           Toolkit.getDefaultToolkit().beep();
           jButton2.setEnabled(false);
        }
        
        
    }


   public int random(int max ,int minm){
       boolean flag=true;
       rand = new Random();
       max=this.max;
       minm=this.minm; 
       int n = rand.nextInt(max) + minm;
        for (int itre=1;itre<=6;itre++){
             if(exc[itre]==n){
                 flag=false;
                 return 0;
             }
       }
       
    
       if(flag==true){
       exc[nextindex]=n;
       ++nextindex;}
          
       return n; 
   }
   
   public void queandans(){
    quese[1]="main()\n{\nint x;\nx=3*4%5;\nprintf(\"%d\",x);\n}";
    quese[2]="main()\n{\nint x;\n x=3 + 4 -7 / 5 % 10;\nprintf(\"x= %d\",x);\n}";
    quese[3]="int main()\n{\nint k=35;\nk=func1(k=func1(k=func1(k)));\nprintf(\"%d\",k);\nreturn 0;\n}\n\nint func1(int k)\n{\nk++;\nreturn k;\n}";
    quese[4]="main()\n{\nint i=3,j;\nj=++i*++i*++i;\nprintf(\"%d\",j);\n}";
    quese[5]="main()\n{\nint a=5;\ndo\n{\n printf(\"%d\",a);\na=-1;\n}while(a>0);\n}";
    quese[6]="main()\n{\nint i=10,j=20,k;\nk=addsub(i,j);\nprintf(\"%d\",k);\n}\naddsub(c,d)\nint c,d;\n{\n int x,y;\nx=c-d;\ny=c+d;\nreturn(x,y);\n}";
    quese[7]="int main()\n{\nfloat fval=7.29;\nprintf(\"%d\",(int)fval);\n return 0;\n}";
    quese[8]="int main()\n{\nint a=100,b=200,c;\nc=(a==100||b>200);\nprintf(\"%d\",c);\nreturn 0;\n}";
    quese[9]="int main()\n{\nint a=100,b=200,c;\nc=(a==100&&b>200);\nprintf(\"%d\",c);\nreturn 0;\n}";
    quese[10]="int main()\n{\nextern int a;\nprintf(\"%d\",a);\nreturn 0;\n}\nint a=20;";
    
    answere[1]="2";
    answere[2]="6";
    answere[3]="38";
    answere[4]="216";
    answere[5]="5";
    answere[6]="30";
    answere[7]="7";
    answere[8]="1";         
    answere[9]="0";
    answere[10]="20";

    quesm[1]="int main()\n{\nchar *str;\nstr=\"%d\";\nstr++;\nstr++;\nprintf(str-2,300);\nreturn 0;\n}";
    quesm[2]="int main()\n{\nfloat fval=7.29;\nprintf(\"%f\",(int)fval);\n return 0;\n}"; /*Check this Question First*/
    quesm[3]="int main()\n{\nint i=2;\nint j=i+(1,2,3,4,5);\nprintf(\"%d\",j);\nreturn 0;\n}";
    quesm[4]="int main()\n{\nprintf(\"%c\",\"abcdefgh\"[4]);\nreturn 0;\n}";
    quesm[5]="int main()\n{\nchar str1[20]=\"Hello\",str2[20]=\"World\";\nprintf(\"%s\",strcpy(str2,strcat(str1,str2)));\nreturn 0;\n}";
    quesm[6]="int main()\n{\nprintf(5+\"Fascimile\");\nreturn 0;\n}";
    quesm[7]="int main()\n{\nint i,*j,k;\ni=3;\nj=&i;\nprintf(\"%d\",i**j*i+*j);\n return 0;\n}";
    quesm[8]="int main()\n{\nprintf(\"%c\",~('C'*-1));\n return 0;\n}"; /*Check Question*/
    quesm[9]="int main()\n{\nfloat a=0.7;\nif(0.7>a)\nprintf(\"Hi\");\nelse\nprintf(\"Hello\");\nreturn 0;\n}";
    quesm[10]="int main()\n{\nfloat a=0.7;\nif(0.7<a)\nprintf(\"Hi\");\nelse\nprintf(\"Hello\");\nreturn 0;\n}";
   
    answerm[1]="300";
    answerm[2]="0.000000";
    answerm[3]="7";
    answerm[4]="e";
    answerm[5]="HelloWorld";
    answerm[6]="mile";
    answerm[7]="30";
    answerm[8]="B";
    answerm[9]="Hi";
    answerm[10]="Hello";
   
    quesh[4]="void fun(void *p);\nint i;\nint main()\n{\n void *vptr;\nvptr=&i;\nfun(vptr);\nreturn 0;\n}\n void fun(void *p)\n{\n int **q;\nq=(int**)&p;\nprintf(\"%d\",**q);\n}";
    quesh[2]="int main()\n{\n unsigned int res;\nres=(64>>(2+1-2))&(~(1<<2));\nprintf(\"%d\",res);\nreturn 0;\n}";
    quesh[3]="#define MAX(a,b,c)(a>b?a>c?a:c:b>c?b:c)\nint main()\n{\nint x;\nx=MAX(3+2,2+7,3+7);\nprintf(\"%d\",x);\nreturn 0;\n}";
    quesh[1]="int main()\n{\n char str[10] =\"Angel\";\nstr[6]=\'d\';\nprintf(\"%s\",str);\nreturn 0;\n}";/*check Quetion*/
    quesh[5]="#define FUN(i,j) i##j\nint main()\n{\n int val1=10,val12=20;\nprintf(\"%d\",FUN(val1,2));\nreturn 0;\n}";
    quesh[6]="int main()\n{\n int n=5;\n printf(\"n=%*d\",n,n);\nreturn 0;\n}\n /*Enter the answer is it is mentioned in printf statement */";
    quesh[7]="int main()\n{\n printf(\"%%%%\");\nreturn 0;\n}";
    quesh[8]="int main()\n{\n char *p;\n p=\"%d\";\np++;\np++;\nprintf(p-2,23);\nreturn 0;\n}";
    quesh[9]="int main()\n{\n int x=10,y=20,z=5,i;\ni=x<y<z;\nprintf(\"%d\",i);\nreturn 0;\n}";
    quesh[10]="int main()\n{\n int x=10,y=20;\nif(!(!x)&&x)\nprintf(\"x=%d\",x);\nelse\nprintf(\"y=%d\",y);\nreturn 0;\n}";
    
    answerh[4]="0";
    answerh[2]="32";
    answerh[3]="10";
    answerh[1]="Angel";
    answerh[5]="20";
    answerh[6]="n=    5";
    answerh[7]="%%";
    answerh[8]="23";
    answerh[9]="1";
    answerh[10]="x=10";
    

    
    
    
   }
   
    public static void main(String args[]) {
      
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainfile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainfile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainfile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainfile1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainfile1(Hex).setVisible(true);
                
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextArea jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    
}
